name: Test backend server
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']
        
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: cd server
      - run: echo "### Install and build backend server"
      - run: npm install
      - run: echo "### Running test"
      - run: npm test