name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@main
      with:
        gradlew_dir: frontend/
        keystore_file: frontend/key/accountability_key.jks
        keystore_password: ${{ secrets.keystore_password }}
        key_alias: ${{ secrets.key_alias }}
        key_password: ${{ secrets.key_password }}
        
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifact-APK
        path: frontend/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          file: frontend/app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.ref }}
          file_glob: true
