name: Test backend server
on: [push]
env:
  GOOGLE_CLIENT_ID: 693940095948-hrfurnccublbbkkmgfu5v4sf5q2nli2a.apps.googleusercontent.com
  STRIPE_SECRET: sk_test_51LFPP5GjSjq6aykF6WBqU4wAwFJv115hfbSKmMOyrTdnpULnkHcmsxw0kzPLT6DvQrgSJoOiLsaphYSU7yIKbzzB007av2eVlb
jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']
    defaults:
      run:
        working-directory: backend
    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: actions/checkout@v1
      - name: Install modules
        run: npm install
      - name: Run tests
        run: ./node_modules/.bin/jest --runInBand --coverage --detectOpenHandles --forceExit
